In [4]:
%pip install pandas numpy scikit-learn matplotlib


[notice] A new release of pip is available: 25.1.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
# ============================================
# 1. IMPORTS
# ============================================

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [6]:
# ============================================
# 2. CARGA DEL DATASET
# ============================================

# Primero usamos el dummy para probar que todo funciona
df = pd.read_csv("../data/features_dummy.csv")

# Cuando esto funcione, cambia la línea anterior por:
# df = pd.read_csv("../data/features.csv")

print("Tamaño del dataset:", df.shape)
df.head()

Tamaño del dataset: (50, 1444)


,node_id,degree,closeness,betweenness,pagerank,eigenvector_centrality,clustering_coef,triangles,kcore,community_louvain,...,word_1424,word_1425,word_1426,word_1427,word_1428,word_1429,word_1430,word_1431,word_1432,class
0,0,8.116262,0.290875,0.001571,0.004541,0.064203,0.294449,3,2,2,...,0,1,1,0,0,1,1,0,0,Case_Based
1,1,19.063572,0.232540,0.031821,0.001198,0.008414,0.385098,2,2,3,...,1,0,1,1,0,0,0,0,0,Reinforcement_Learning
2,2,14.907885,0.281850,0.015718,0.000724,0.016163,0.851137,6,1,4,...,0,1,0,0,1,1,1,0,0,Rule_Learning
3,3,12.374511,0.268448,0.025429,0.002447,0.089855,0.316922,7,3,4,...,1,1,1,0,1,1,0,1,0,Probabilistic_Methods
4,4,3.964354,0.179370,0.045378,0.004928,0.060643,0.169493,3,2,3,...,1,0,1,0,1,0,0,1,1,Genetic_Algorithms


In [7]:
# ============================================
# 4. COMPROBAR LA VARIABLE OBJETIVO
# ============================================

# La columna que queremos predecir debería ser 'class'
target = "class"

print("Distribución de clases:")
print(df[target].value_counts())

Distribución de clases:
class
Reinforcement_Learning    14
Theory                     9
Genetic_Algorithms         6
Neural_Networks            6
Case_Based                 5
Rule_Learning              5
Probabilistic_Methods      5
Name: count, dtype: int64


In [8]:
# ============================================
# 5. SEPARAR X E y
# ============================================

# y = lo que queremos predecir
y = df[target]

# X = columnas que usamos para predecir
X = df.drop(columns=[target])

# Quitamos node_id si existe, porque es solo un identificador
if "node_id" in X.columns:
    X = X.drop(columns=["node_id"])

print("Tamaño de X:", X.shape)
print("Tamaño de y:", y.shape)

X.head()

Tamaño de X: (50, 1442)
Tamaño de y: (50,)


,degree,closeness,betweenness,pagerank,eigenvector_centrality,clustering_coef,triangles,kcore,community_louvain,word_0,...,word_1423,word_1424,word_1425,word_1426,word_1427,word_1428,word_1429,word_1430,word_1431,word_1432
0,8.116262,0.290875,0.001571,0.004541,0.064203,0.294449,3,2,2,0,...,0,0,1,1,0,0,1,1,0,0
1,19.063572,0.232540,0.031821,0.001198,0.008414,0.385098,2,2,3,0,...,0,1,0,1,1,0,0,0,0,0
2,14.907885,0.281850,0.015718,0.000724,0.016163,0.851137,6,1,4,1,...,1,0,1,0,0,1,1,1,0,0
3,12.374511,0.268448,0.025429,0.002447,0.089855,0.316922,7,3,4,1,...,0,1,1,1,0,1,1,0,1,0
4,3.964354,0.179370,0.045378,0.004928,0.060643,0.169493,3,2,3,0,...,0,1,0,1,0,1,0,0,1,1


In [9]:
# ============================================
# 6. DIVISIÓN TRAIN / TEST
# ============================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Tamaño entrenamiento:", X_train.shape)
print("Tamaño test:", X_test.shape)

Tamaño entrenamiento: (40, 1442)
Tamaño test: (10, 1442)


In [10]:
# ============================================
# 7. PRIMER MODELO: ÁRBOL DE DECISIÓN
# ============================================

modelo = DecisionTreeClassifier(random_state=42)

modelo.fit(X_train, y_train)

y_pred = modelo.predict(X_test)

In [11]:
# ============================================
# 8. EVALUACIÓN DEL MODELO
# ============================================

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nClassification report:")
print(classification_report(y_test, y_pred))

print("\nMatriz de confusión:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.0

Classification report:
                        precision    recall  f1-score   support

            Case_Based       0.00      0.00      0.00       0.0
    Genetic_Algorithms       0.00      0.00      0.00       2.0
       Neural_Networks       0.00      0.00      0.00       3.0
 Probabilistic_Methods       0.00      0.00      0.00       1.0
Reinforcement_Learning       0.00      0.00      0.00       1.0
         Rule_Learning       0.00      0.00      0.00       2.0
                Theory       0.00      0.00      0.00       1.0

              accuracy                           0.00      10.0
             macro avg       0.00      0.00      0.00      10.0
          weighted avg       0.00      0.00      0.00      10.0


Matriz de confusión:
[[0 0 0 0 0 0 0]
 [0 0 0 1 0 0 1]
 [1 0 0 1 0 1 0]
 [0 0 0 0 1 0 0]
 [0 0 0 1 0 0 0]
 [0 1 0 1 0 0 0]
 [0 1 0 0 0 0 0]]


c:\Users\samuf\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\samuf\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\samuf\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, mo